/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAjudaRouteImport } from './routes/app/ajuda'
import { Route as AppComunidadeRouteImport } from './routes/app/comunidade'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppCursosRouteImport } from './routes/app/cursos'
import { Route as AppDesempenhoRouteImport } from './routes/app/desempenho'
import { Route as AppLivesRouteImport } from './routes/app/lives'
import { Route as AppMentoriasRouteImport } from './routes/app/mentorias'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as AppPlanejamentoRouteImport } from './routes/app/planejamento'
import { Route as AppQuestoesRouteImport } from './routes/app/questoes'
import { Route as AppSimuladosRouteImport } from './routes/app/simulados'
import { Route as ClipperIndexRouteImport } from './routes/clipper/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as InfluencerIndexRouteImport } from './routes/influencer/index'
import { Route as MentorIndexRouteImport } from './routes/mentor/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjudaRoute = AppAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComunidadeRoute = AppComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDesempenhoRoute = AppDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLivesRoute = AppLivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMentoriasRoute = AppMentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuestoesRoute = AppQuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSimuladosRoute = AppSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AppRouteRoute,
} as any)
const ClipperIndexRoute = ClipperIndexRouteImport.update({
  id: '/clipper/',
  path: '/clipper/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerIndexRoute = InfluencerIndexRouteImport.update({
  id: '/influencer/',
  path: '/influencer/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/mentor/',
  path: '/mentor/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/lives': typeof AppLivesRoute
  '/app/mentorias': typeof AppMentoriasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/questoes': typeof AppQuestoesRoute
  '/app/simulados': typeof AppSimuladosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/clipper/': typeof ClipperIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/support/': typeof SupportIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/lives': typeof AppLivesRoute
  '/app/mentorias': typeof AppMentoriasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/questoes': typeof AppQuestoesRoute
  '/app/simulados': typeof AppSimuladosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/clipper': typeof ClipperIndexRoute
  '/editor': typeof EditorIndexRoute
  '/influencer': typeof InfluencerIndexRoute
  '/mentor': typeof MentorIndexRoute
  '/support': typeof SupportIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/comunidade': typeof AppComunidadeRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/cursos': typeof AppCursosRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/lives': typeof AppLivesRoute
  '/app/mentorias': typeof AppMentoriasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/planejamento': typeof AppPlanejamentoRoute
  '/app/questoes': typeof AppQuestoesRoute
  '/app/simulados': typeof AppSimuladosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/clipper/': typeof ClipperIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/mentor/': typeof MentorIndexRoute
  '/support/': typeof SupportIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/ajuda'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/desempenho'
    | '/app/lives'
    | '/app/mentorias'
    | '/app/perfil'
    | '/app/planejamento'
    | '/app/questoes'
    | '/app/simulados'
    | '/admin/'
    | '/app/'
    | '/clipper/'
    | '/editor/'
    | '/influencer/'
    | '/mentor/'
    | '/support/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/ajuda'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/desempenho'
    | '/app/lives'
    | '/app/mentorias'
    | '/app/perfil'
    | '/app/planejamento'
    | '/app/questoes'
    | '/app/simulados'
    | '/admin'
    | '/app'
    | '/clipper'
    | '/editor'
    | '/influencer'
    | '/mentor'
    | '/support'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/ajuda'
    | '/app/comunidade'
    | '/app/configuracoes'
    | '/app/cursos'
    | '/app/desempenho'
    | '/app/lives'
    | '/app/mentorias'
    | '/app/perfil'
    | '/app/planejamento'
    | '/app/questoes'
    | '/app/simulados'
    | '/admin/'
    | '/app/'
    | '/clipper/'
    | '/editor/'
    | '/influencer/'
    | '/mentor/'
    | '/support/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClipperIndexRoute: typeof ClipperIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  InfluencerIndexRoute: typeof InfluencerIndexRoute
  MentorIndexRoute: typeof MentorIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ajuda': {
      id: '/app/ajuda'
      path: '/ajuda'
      fullPath: '/app/ajuda'
      preLoaderRoute: typeof AppAjudaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/comunidade': {
      id: '/app/comunidade'
      path: '/comunidade'
      fullPath: '/app/comunidade'
      preLoaderRoute: typeof AppComunidadeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cursos': {
      id: '/app/cursos'
      path: '/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/desempenho': {
      id: '/app/desempenho'
      path: '/desempenho'
      fullPath: '/app/desempenho'
      preLoaderRoute: typeof AppDesempenhoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lives': {
      id: '/app/lives'
      path: '/lives'
      fullPath: '/app/lives'
      preLoaderRoute: typeof AppLivesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mentorias': {
      id: '/app/mentorias'
      path: '/mentorias'
      fullPath: '/app/mentorias'
      preLoaderRoute: typeof AppMentoriasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/planejamento': {
      id: '/app/planejamento'
      path: '/planejamento'
      fullPath: '/app/planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/questoes': {
      id: '/app/questoes'
      path: '/questoes'
      fullPath: '/app/questoes'
      preLoaderRoute: typeof AppQuestoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/simulados': {
      id: '/app/simulados'
      path: '/simulados'
      fullPath: '/app/simulados'
      preLoaderRoute: typeof AppSimuladosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/clipper/': {
      id: '/clipper/'
      path: '/clipper'
      fullPath: '/clipper/'
      preLoaderRoute: typeof ClipperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/': {
      id: '/influencer/'
      path: '/influencer'
      fullPath: '/influencer/'
      preLoaderRoute: typeof InfluencerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/mentor'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAjudaRoute: typeof AppAjudaRoute
  AppComunidadeRoute: typeof AppComunidadeRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCursosRoute: typeof AppCursosRoute
  AppDesempenhoRoute: typeof AppDesempenhoRoute
  AppLivesRoute: typeof AppLivesRoute
  AppMentoriasRoute: typeof AppMentoriasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppQuestoesRoute: typeof AppQuestoesRoute
  AppSimuladosRoute: typeof AppSimuladosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAjudaRoute: AppAjudaRoute,
  AppComunidadeRoute: AppComunidadeRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCursosRoute: AppCursosRoute,
  AppDesempenhoRoute: AppDesempenhoRoute,
  AppLivesRoute: AppLivesRoute,
  AppMentoriasRoute: AppMentoriasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppQuestoesRoute: AppQuestoesRoute,
  AppSimuladosRoute: AppSimuladosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClipperIndexRoute: ClipperIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  InfluencerIndexRoute: InfluencerIndexRoute,
  MentorIndexRoute: MentorIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
